/*
 * The starting catalogue: the tiles you tap instead of typing.
 *
 * This is data, not logic. It lives in the app rather than only in SQL so the
 * seed can be regenerated, re-ordered or translated without a database
 * migration, and so the ordering below is reviewable in one place.
 *
 * Three fields per item:
 *
 *   name       what's shown on the tile.
 *   icon       a slug from src/lib/icons.ts. Omitted where no drawing fits, and
 *              the tile then shows the item's outlined initial instead — a real
 *              part of the design, not a gap. About 15 items sit there.
 *   suggested  rank in the "typical stuff" order shown before the app has
 *              learned anything. Omitted for all but ~20 items.
 *
 * Category order is the order they appear in the grid, and it is a hand-picked
 * guess at how a supermarket is walked — produce first, freezer and household
 * last. NIU.md §4.1 wants this order *learned* from the order things get ticked
 * off, per shop. That needs tick history to exist first, so this is the sensible
 * default it starts from and later gets replaced by.
 *
 * Names are English (confirmed), lowercase, singular unless the thing is
 * normally bought as a plural ("eggs"). Keeping that consistent matters because
 * the unique index in 0002 is on lower(trim(name)) — "Milk" and "milk" are the
 * same tile.
 */

import type { IconName } from './icons'

export interface SeedCategory {
  readonly name: string
  /** Icon slug for the category header row — must exist in icons.ts. */
  readonly icon: IconName
  readonly items: readonly SeedItem[]
}

export interface SeedItem {
  readonly name: string
  /** Slug from the icon set. Absent means "draw the initial instead". */
  readonly icon?: IconName
  /** Position in the pre-learning suggested order. Absent means unranked. */
  readonly suggested?: number
}

export const CATALOGUE_SEED: readonly SeedCategory[] = [
  {
    name: 'Fruit & vegetables',
    icon: 'carrot',
    items: [
      { name: 'apples', icon: 'apple', suggested: 14 },
      { name: 'bananas', icon: 'banana', suggested: 4 },
      { name: 'oranges', icon: 'citrus' },
      { name: 'lemons', icon: 'citrus' },
      { name: 'limes', icon: 'citrus' },
      { name: 'strawberries', icon: 'strawberry' },
      { name: 'raspberries', icon: 'strawberry' },
      { name: 'blueberries', icon: 'strawberry' },
      { name: 'grapes', icon: 'grapes' },
      { name: 'cherries', icon: 'strawberry' },
      { name: 'melon', icon: 'melon' },
      { name: 'watermelon', icon: 'melon' },
      { name: 'peaches', icon: 'apple' },
      { name: 'pears', icon: 'apple' },
      { name: 'plums', icon: 'apple' },
      { name: 'apricots', icon: 'apple' },
      { name: 'figs', icon: 'apple' },
      { name: 'pineapple', icon: 'melon' },
      { name: 'kiwi', icon: 'melon' },
      { name: 'mango', icon: 'melon' },
      { name: 'pomegranate', icon: 'apple' },
      { name: 'avocado', icon: 'melon' },
      { name: 'tomatoes', icon: 'tomato', suggested: 5 },
      { name: 'cherry tomatoes', icon: 'tomato' },
      { name: 'potatoes', icon: 'potato', suggested: 7 },
      { name: 'sweet potato', icon: 'potato' },
      { name: 'onions', icon: 'onion', suggested: 6 },
      { name: 'spring onions', icon: 'onion' },
      { name: 'garlic', icon: 'garlic' },
      { name: 'carrots', icon: 'carrot', suggested: 20 },
      { name: 'peppers', icon: 'pepper' },
      { name: 'chillies', icon: 'pepper' },
      { name: 'courgette', icon: 'cucumber' },
      { name: 'aubergine', icon: 'cucumber' },
      { name: 'cucumber', icon: 'cucumber' },
      { name: 'lettuce', icon: 'lettuce', suggested: 19 },
      { name: 'rocket', icon: 'lettuce' },
      { name: 'spinach', icon: 'lettuce' },
      { name: 'broccoli', icon: 'broccoli' },
      { name: 'cauliflower', icon: 'broccoli' },
      { name: 'cabbage', icon: 'broccoli' },
      { name: 'brussels sprouts', icon: 'broccoli' },
      { name: 'asparagus', icon: 'lettuce' },
      { name: 'artichoke', icon: 'broccoli' },
      { name: 'fennel', icon: 'broccoli' },
      { name: 'mushrooms', icon: 'mushroom' },
      { name: 'sweetcorn', icon: 'corn' },
      { name: 'green beans' },
      { name: 'peas' },
      { name: 'leek', icon: 'onion' },
      { name: 'celery', icon: 'lettuce' },
      { name: 'radish', icon: 'cucumber' },
      { name: 'beetroot', icon: 'cucumber' },
      { name: 'pumpkin', icon: 'cucumber' },
      { name: 'ginger', icon: 'cucumber' },
      { name: 'parsley', icon: 'herbs' },
      { name: 'basil', icon: 'herbs' },
      { name: 'coriander', icon: 'herbs' },
      { name: 'mint', icon: 'herbs' },
      { name: 'rosemary', icon: 'herbs' },
      { name: 'salad bag', icon: 'lettuce' },
    ],
  },
  {
    name: 'Bakery',
    icon: 'bread',
    items: [
      { name: 'bread', icon: 'bread', suggested: 2 },
      { name: 'baguette', icon: 'baguette' },
      { name: 'sliced bread', icon: 'bread' },
      { name: 'wholemeal bread', icon: 'bread' },
      { name: 'sourdough', icon: 'bread' },
      { name: 'bread rolls', icon: 'bread' },
      { name: 'ciabatta', icon: 'bread' },
      { name: 'focaccia', icon: 'bread' },
      { name: 'brioche', icon: 'bread' },
      { name: 'croissants', icon: 'croissant' },
      { name: 'bagels', icon: 'cake' },
      { name: 'pitta bread', icon: 'bread' },
      { name: 'naan', icon: 'bread' },
      { name: 'tortillas', icon: 'bread' },
      { name: 'pastries', icon: 'croissant' },
      { name: 'cake', icon: 'cake' },
      { name: 'muffins', icon: 'cake' },
      { name: 'doughnuts', icon: 'croissant' },
      { name: 'scones', icon: 'bread' },
      { name: 'biscuits', icon: 'cookie' },
    ],
  },
  {
    name: 'Dairy & eggs',
    icon: 'milk',
    items: [
      { name: 'milk', icon: 'milk', suggested: 1 },
      { name: 'semi-skimmed milk', icon: 'milk' },
      { name: 'oat milk', icon: 'milk' },
      { name: 'almond milk', icon: 'milk' },
      { name: 'soy milk', icon: 'milk' },
      { name: 'eggs', icon: 'egg', suggested: 3 },
      { name: 'butter', icon: 'butter', suggested: 12 },
      { name: 'margarine', icon: 'butter' },
      { name: 'cheese', icon: 'cheese', suggested: 11 },
      { name: 'cheddar', icon: 'cheese' },
      { name: 'grated cheese', icon: 'cheese' },
      { name: 'goat cheese', icon: 'cheese' },
      { name: 'blue cheese', icon: 'cheese' },
      { name: 'brie', icon: 'cheese' },
      { name: 'manchego', icon: 'cheese' },
      { name: 'mozzarella', icon: 'cheese' },
      { name: 'parmesan', icon: 'cheese' },
      { name: 'feta', icon: 'cheese' },
      { name: 'ricotta', icon: 'cheese' },
      { name: 'mascarpone', icon: 'cheese' },
      { name: 'cream cheese', icon: 'cheese' },
      { name: 'cottage cheese', icon: 'cheese' },
      { name: 'yoghurt', icon: 'yoghurt', suggested: 13 },
      { name: 'greek yoghurt', icon: 'yoghurt' },
      { name: 'kefir', icon: 'yoghurt' },
      { name: 'cream', icon: 'yoghurt' },
      { name: 'sour cream', icon: 'yoghurt' },
      { name: 'creme fraiche', icon: 'yoghurt' },
      { name: 'custard', icon: 'yoghurt' },
      { name: 'condensed milk', icon: 'milk' },
    ],
  },
  {
    name: 'Meat & fish',
    icon: 'meat',
    items: [
      { name: 'chicken breast', icon: 'chicken', suggested: 8 },
      { name: 'chicken thighs', icon: 'chicken' },
      { name: 'chicken wings', icon: 'chicken' },
      { name: 'whole chicken', icon: 'chicken' },
      { name: 'turkey', icon: 'chicken' },
      { name: 'minced beef', icon: 'meat' },
      { name: 'beef steak', icon: 'meat' },
      { name: 'beef stewing', icon: 'meat' },
      { name: 'burger patties', icon: 'meat' },
      { name: 'meatballs', icon: 'meat' },
      { name: 'pork chops', icon: 'meat' },
      { name: 'pork belly', icon: 'meat' },
      { name: 'ribs', icon: 'meat' },
      { name: 'lamb', icon: 'meat' },
      { name: 'veal', icon: 'meat' },
      { name: 'duck', icon: 'chicken' },
      { name: 'rabbit', icon: 'meat' },
      { name: 'sausages', icon: 'sausage' },
      { name: 'bacon', icon: 'sausage' },
      { name: 'ham', icon: 'sausage' },
      { name: 'chorizo', icon: 'sausage' },
      { name: 'salami', icon: 'sausage' },
      { name: 'pate', icon: 'sausage' },
      { name: 'black pudding', icon: 'sausage' },
      { name: 'salmon', icon: 'fish' },
      { name: 'smoked salmon', icon: 'fish' },
      { name: 'white fish', icon: 'fish' },
      { name: 'cod', icon: 'fish' },
      { name: 'hake', icon: 'fish' },
      { name: 'sea bass', icon: 'fish' },
      { name: 'tuna steak', icon: 'meat' },
      { name: 'sardines', icon: 'fish' },
      { name: 'anchovies', icon: 'fish' },
      { name: 'prawns', icon: 'shrimp' },
      { name: 'mussels', icon: 'shrimp' },
      { name: 'clams', icon: 'shrimp' },
      { name: 'squid', icon: 'shrimp' },
      { name: 'octopus', icon: 'shrimp' },
      { name: 'crab', icon: 'shrimp' },
    ],
  },
  {
    name: 'Pantry',
    icon: 'can',
    items: [
      { name: 'pasta', icon: 'pasta', suggested: 9 },
      { name: 'spaghetti', icon: 'pasta' },
      { name: 'lasagne sheets', icon: 'pasta' },
      { name: 'gnocchi', icon: 'pasta' },
      { name: 'rice', icon: 'rice', suggested: 10 },
      { name: 'risotto rice', icon: 'rice' },
      { name: 'noodles', icon: 'pasta' },
      { name: 'rice noodles', icon: 'pasta' },
      { name: 'couscous', icon: 'pasta' },
      { name: 'quinoa', icon: 'rice' },
      { name: 'polenta', icon: 'rice' },
      { name: 'bulgur', icon: 'rice' },
      { name: 'lentils', icon: 'can' },
      { name: 'chickpeas', icon: 'can' },
      { name: 'kidney beans', icon: 'can' },
      { name: 'white beans', icon: 'can' },
      { name: 'tinned tomatoes', icon: 'tomato', suggested: 21 },
      { name: 'passata', icon: 'can' },
      { name: 'tomato sauce', icon: 'sauce' },
      { name: 'tomato puree' },
      { name: 'tinned tuna', icon: 'fish' },
      { name: 'tinned sweetcorn', icon: 'can' },
      { name: 'coconut milk', icon: 'milk' },
      { name: 'olive oil', icon: 'oil', suggested: 15 },
      { name: 'sunflower oil', icon: 'oil' },
      { name: 'sesame oil', icon: 'oil' },
      { name: 'vinegar', icon: 'oil' },
      { name: 'balsamic vinegar', icon: 'oil' },
      { name: 'salt', icon: 'salt' },
      { name: 'pepper', icon: 'salt' },
      { name: 'sugar', icon: 'salt' },
      { name: 'brown sugar', icon: 'salt' },
      { name: 'icing sugar', icon: 'salt' },
      { name: 'flour', icon: 'salt' },
      { name: 'cornflour', icon: 'corn' },
      { name: 'baking powder', icon: 'salt' },
      { name: 'yeast', icon: 'salt' },
      { name: 'vanilla', icon: 'spice' },
      { name: 'cocoa powder', icon: 'spice' },
      { name: 'chocolate chips', icon: 'juice' },
      { name: 'honey', icon: 'honey' },
      { name: 'jam', icon: 'honey' },
      { name: 'marmalade', icon: 'honey' },
      { name: 'peanut butter', icon: 'honey' },
      { name: 'chocolate spread', icon: 'honey' },
      { name: 'tahini', icon: 'honey' },
      { name: 'cereal', icon: 'cereal' },
      { name: 'porridge oats', icon: 'cereal' },
      { name: 'muesli', icon: 'cereal' },
      { name: 'granola', icon: 'cereal' },
      { name: 'stock cubes', icon: 'sauce' },
      { name: 'soy sauce', icon: 'sauce' },
      { name: 'fish sauce', icon: 'fish' },
      { name: 'worcestershire sauce', icon: 'sauce' },
      { name: 'hot sauce', icon: 'sauce' },
      { name: 'bbq sauce', icon: 'sauce' },
      { name: 'mustard', icon: 'sauce' },
      { name: 'mayonnaise', icon: 'sauce' },
      { name: 'ketchup', icon: 'sauce' },
      { name: 'pesto', icon: 'jar' },
      { name: 'curry paste', icon: 'sauce' },
      { name: 'harissa', icon: 'sauce' },
      { name: 'olives', icon: 'jar' },
      { name: 'pickles', icon: 'jar' },
      { name: 'capers', icon: 'jar' },
      { name: 'nuts', icon: 'nuts' },
      { name: 'almonds', icon: 'nuts' },
      { name: 'walnuts', icon: 'nuts' },
      { name: 'cashews', icon: 'nuts' },
      { name: 'pistachios', icon: 'nuts' },
      { name: 'raisins', icon: 'grapes' },
      { name: 'dates', icon: 'nuts' },
      { name: 'dried apricots' },
      { name: 'chia seeds', icon: 'nuts' },
      { name: 'sunflower seeds', icon: 'nuts' },
      { name: 'pumpkin seeds', icon: 'cucumber' },
      { name: 'spices', icon: 'spice' },
      { name: 'paprika', icon: 'spice' },
      { name: 'oregano', icon: 'herbs' },
      { name: 'thyme', icon: 'herbs' },
      { name: 'bay leaves', icon: 'herbs' },
      { name: 'cinnamon', icon: 'spice' },
      { name: 'nutmeg', icon: 'spice' },
      { name: 'cumin', icon: 'spice' },
      { name: 'turmeric', icon: 'spice' },
      { name: 'curry powder', icon: 'spice' },
      { name: 'chilli flakes', icon: 'spice' },
      { name: 'garlic powder', icon: 'spice' },
      { name: 'breadcrumbs', icon: 'salt' },
    ],
  },
  {
    name: 'Frozen',
    icon: 'frozen',
    items: [
      { name: 'frozen peas', icon: 'frozen' },
      { name: 'frozen spinach', icon: 'lettuce' },
      { name: 'frozen vegetables', icon: 'frozen' },
      { name: 'frozen berries', icon: 'frozen' },
      { name: 'frozen chips', icon: 'frozen' },
      { name: 'frozen pizza', icon: 'frozen' },
      { name: 'frozen fish', icon: 'fish' },
      { name: 'frozen prawns', icon: 'shrimp' },
      { name: 'frozen burgers', icon: 'frozen' },
      { name: 'chicken nuggets', icon: 'chicken' },
      { name: 'frozen pastry', icon: 'frozen' },
      { name: 'frozen bread', icon: 'frozen' },
      { name: 'ice cream', icon: 'iceCream' },
      { name: 'sorbet', icon: 'iceCream' },
      { name: 'ice cubes', icon: 'iceCream' },
    ],
  },
  {
    name: 'Drinks',
    icon: 'water',
    items: [
      { name: 'water', icon: 'water', suggested: 22 },
      { name: 'sparkling water', icon: 'water' },
      { name: 'coconut water', icon: 'water' },
      { name: 'orange juice', icon: 'juice' },
      { name: 'apple juice', icon: 'juice' },
      { name: 'lemonade', icon: 'juice' },
      { name: 'cola', icon: 'juice' },
      { name: 'soft drinks', icon: 'juice' },
      { name: 'tonic water', icon: 'juice' },
      { name: 'iced tea', icon: 'tea' },
      { name: 'energy drink', icon: 'juice' },
      { name: 'kombucha', icon: 'beer' },
      { name: 'coffee', icon: 'coffee', suggested: 16 },
      { name: 'ground coffee', icon: 'coffee' },
      { name: 'coffee capsules', icon: 'coffee' },
      { name: 'tea', icon: 'tea' },
      { name: 'herbal tea', icon: 'tea' },
      { name: 'hot chocolate', icon: 'coffee' },
      { name: 'red wine', icon: 'wine' },
      { name: 'white wine', icon: 'wine' },
      { name: 'rose wine', icon: 'wine' },
      { name: 'cava', icon: 'wine' },
      { name: 'beer', icon: 'beer' },
      { name: 'cider', icon: 'beer' },
      { name: 'vermouth', icon: 'wine' },
      { name: 'gin', icon: 'wine' },
      { name: 'whisky', icon: 'wine' },
      { name: 'rum', icon: 'wine' },
      { name: 'vodka', icon: 'wine' },
    ],
  },
  {
    name: 'Snacks',
    icon: 'chocolate',
    items: [
      { name: 'crisps', icon: 'crisps' },
      { name: 'tortilla chips', icon: 'crisps' },
      { name: 'nachos', icon: 'crisps' },
      { name: 'pretzels', icon: 'crisps' },
      { name: 'popcorn', icon: 'crisps' },
      { name: 'crackers', icon: 'cookie' },
      { name: 'breadsticks', icon: 'baguette' },
      { name: 'rice cakes', icon: 'cookie' },
      { name: 'chocolate', icon: 'juice' },
      { name: 'sweets', icon: 'chocolate' },
      { name: 'chewing gum', icon: 'chocolate' },
      { name: 'marshmallows', icon: 'chocolate' },
      { name: 'cereal bars', icon: 'cereal' },
      { name: 'dried fruit', icon: 'crisps' },
      { name: 'salsa', icon: 'jar' },
      { name: 'guacamole', icon: 'jar' },
      { name: 'hummus', icon: 'jar' },
    ],
  },
  {
    name: 'Household',
    icon: 'detergent',
    items: [
      { name: 'toilet paper', icon: 'toiletPaper', suggested: 17 },
      { name: 'kitchen roll', icon: 'toiletPaper' },
      { name: 'tissues', icon: 'toiletPaper' },
      { name: 'bin bags', icon: 'binBag' },
      { name: 'food bags', icon: 'binBag' },
      { name: 'freezer bags', icon: 'binBag' },
      { name: 'cling film', icon: 'foil' },
      { name: 'aluminium foil', icon: 'foil' },
      { name: 'baking paper', icon: 'foil' },
      { name: 'washing up liquid', icon: 'detergent', suggested: 18 },
      { name: 'dishwasher tablets', icon: 'detergent' },
      { name: 'dish cloths', icon: 'sponge' },
      { name: 'sponges', icon: 'sponge' },
      { name: 'scourers', icon: 'sponge' },
      { name: 'rubber gloves', icon: 'sponge' },
      { name: 'laundry detergent', icon: 'detergent' },
      { name: 'fabric softener', icon: 'detergent' },
      { name: 'stain remover', icon: 'detergent' },
      { name: 'surface cleaner' },
      { name: 'bleach' },
      { name: 'toilet cleaner' },
      { name: 'oven cleaner' },
      { name: 'window cleaner' },
      { name: 'air freshener' },
      { name: 'insect spray' },
      { name: 'batteries', icon: 'battery' },
      { name: 'light bulbs', icon: 'bulb' },
      { name: 'candles', icon: 'candle' },
      { name: 'matches', icon: 'candle' },
      { name: 'tape' },
    ],
  },
  {
    name: 'Personal care',
    icon: 'soap',
    items: [
      { name: 'shampoo', icon: 'shampoo' },
      { name: 'conditioner', icon: 'shampoo' },
      { name: 'shower gel', icon: 'soap' },
      { name: 'soap', icon: 'soap' },
      { name: 'hand soap', icon: 'soap' },
      { name: 'hand sanitiser', icon: 'soap' },
      { name: 'hand cream', icon: 'soap' },
      { name: 'moisturiser', icon: 'soap' },
      { name: 'lip balm', icon: 'soap' },
      { name: 'sun cream', icon: 'soap' },
      { name: 'deodorant' },
      { name: 'toothpaste', icon: 'toothpaste' },
      { name: 'toothbrush', icon: 'toothbrush' },
      { name: 'mouthwash', icon: 'toothpaste' },
      { name: 'dental floss', icon: 'toothpaste' },
      { name: 'razors', icon: 'toothbrush' },
      { name: 'shaving foam' },
      { name: 'hairbrush', icon: 'toothbrush' },
      { name: 'hair gel' },
      { name: 'cotton buds', icon: 'sponge' },
      { name: 'cotton pads', icon: 'sponge' },
      { name: 'wet wipes', icon: 'sponge' },
      { name: 'nail clippers', icon: 'toothbrush' },
      { name: 'sanitary pads', icon: 'pills' },
      { name: 'tampons', icon: 'pills' },
      { name: 'plasters', icon: 'pills' },
      { name: 'antiseptic cream', icon: 'pills' },
      { name: 'paracetamol', icon: 'pills' },
      { name: 'ibuprofen', icon: 'pills' },
      { name: 'throat lozenges', icon: 'pills' },
      { name: 'vitamins', icon: 'pills' },
    ],
  },
]

/** Every seed item flattened, with its category and grid position attached. */
export function flattenSeed(): {
  name: string
  category: string
  icon: string | null
  sortOrder: number
  suggestedRank: number | null
}[] {
  const rows: {
    name: string
    category: string
    icon: string | null
    sortOrder: number
    suggestedRank: number | null
  }[] = []

  CATALOGUE_SEED.forEach((category, categoryIndex) => {
    category.items.forEach((item, itemIndex) => {
      rows.push({
        name: item.name,
        category: category.name,
        icon: item.icon ?? null,
        // Category first, then position within it. The 1000 gap leaves room to
        // insert items into a category later without renumbering everything.
        sortOrder: categoryIndex * 1000 + itemIndex,
        suggestedRank: item.suggested ?? null,
      })
    })
  })

  return rows
}

/** Icon slug for a category header, by category name. */
export function categoryIcon(categoryName: string): string | null {
  return CATALOGUE_SEED.find((c) => c.name === categoryName)?.icon ?? null
}
