/*
 * The starting catalogue: the tiles you tap instead of typing.
 *
 * This is data, not logic. It lives in the app rather than only in SQL so the
 * seed can be regenerated, re-ordered or translated without a database
 * migration, and so the ordering below is reviewable in one place.
 *
 * Category order is the order they appear in the grid, and it is a hand-picked
 * guess at how a supermarket is walked — produce first, freezer and household
 * last. NIU.md §4.1 wants this order *learned* from the order things get ticked
 * off, per shop. That needs tick history to exist first, so this is the sensible
 * default it starts from and later gets replaced by.
 *
 * Names are English (confirmed), lowercase, singular unless the thing is
 * normally bought as a plural ("eggs"). Keeping that consistent matters because
 * the unique index in 0002 is on lower(trim(name)) — "Milk" and "milk" are the
 * same tile.
 */

export interface SeedCategory {
  readonly name: string
  /** Emoji shown on the category header. */
  readonly icon: string
  readonly items: readonly SeedItem[]
}

export interface SeedItem {
  readonly name: string
  /** Emoji tile. Items without a good emoji get a first-letter tile instead. */
  readonly icon?: string
}

export const CATALOGUE_SEED: readonly SeedCategory[] = [
  {
    name: 'Fruit & vegetables',
    icon: '🥬',
    items: [
      { name: 'apples', icon: '🍎' },
      { name: 'bananas', icon: '🍌' },
      { name: 'oranges', icon: '🍊' },
      { name: 'lemons', icon: '🍋' },
      { name: 'limes' },
      { name: 'strawberries', icon: '🍓' },
      { name: 'raspberries' },
      { name: 'blueberries', icon: '🫐' },
      { name: 'grapes', icon: '🍇' },
      { name: 'cherries', icon: '🍒' },
      { name: 'melon', icon: '🍈' },
      { name: 'watermelon', icon: '🍉' },
      { name: 'peaches', icon: '🍑' },
      { name: 'pears', icon: '🍐' },
      { name: 'plums' },
      { name: 'apricots' },
      { name: 'figs' },
      { name: 'pineapple', icon: '🍍' },
      { name: 'kiwi', icon: '🥝' },
      { name: 'mango', icon: '🥭' },
      { name: 'pomegranate' },
      { name: 'avocado', icon: '🥑' },
      { name: 'tomatoes', icon: '🍅' },
      { name: 'cherry tomatoes', icon: '🍅' },
      { name: 'potatoes', icon: '🥔' },
      { name: 'sweet potato', icon: '🍠' },
      { name: 'onions', icon: '🧅' },
      { name: 'spring onions' },
      { name: 'garlic', icon: '🧄' },
      { name: 'carrots', icon: '🥕' },
      { name: 'peppers', icon: '🫑' },
      { name: 'chillies', icon: '🌶️' },
      { name: 'courgette', icon: '🥒' },
      { name: 'aubergine', icon: '🍆' },
      { name: 'cucumber', icon: '🥒' },
      { name: 'lettuce', icon: '🥬' },
      { name: 'rocket' },
      { name: 'spinach', icon: '🥬' },
      { name: 'broccoli', icon: '🥦' },
      { name: 'cauliflower' },
      { name: 'cabbage' },
      { name: 'brussels sprouts' },
      { name: 'asparagus' },
      { name: 'artichoke' },
      { name: 'fennel' },
      { name: 'mushrooms', icon: '🍄' },
      { name: 'sweetcorn', icon: '🌽' },
      { name: 'green beans' },
      { name: 'peas' },
      { name: 'leek' },
      { name: 'celery' },
      { name: 'radish' },
      { name: 'beetroot' },
      { name: 'pumpkin', icon: '🎃' },
      { name: 'ginger' },
      { name: 'parsley', icon: '🌿' },
      { name: 'basil', icon: '🌿' },
      { name: 'coriander', icon: '🌿' },
      { name: 'mint', icon: '🌿' },
      { name: 'rosemary', icon: '🌿' },
      { name: 'salad bag' },
    ],
  },
  {
    name: 'Bakery',
    icon: '🥖',
    items: [
      { name: 'bread', icon: '🍞' },
      { name: 'baguette', icon: '🥖' },
      { name: 'sliced bread' },
      { name: 'wholemeal bread' },
      { name: 'sourdough' },
      { name: 'bread rolls' },
      { name: 'ciabatta' },
      { name: 'focaccia' },
      { name: 'brioche' },
      { name: 'croissants', icon: '🥐' },
      { name: 'bagels', icon: '🥯' },
      { name: 'pitta bread' },
      { name: 'naan' },
      { name: 'tortillas', icon: '🌯' },
      { name: 'pastries', icon: '🥧' },
      { name: 'cake', icon: '🍰' },
      { name: 'muffins', icon: '🧁' },
      { name: 'doughnuts', icon: '🍩' },
      { name: 'scones' },
      { name: 'biscuits', icon: '🍪' },
    ],
  },
  {
    name: 'Dairy & eggs',
    icon: '🥛',
    items: [
      { name: 'milk', icon: '🥛' },
      { name: 'semi-skimmed milk' },
      { name: 'oat milk' },
      { name: 'almond milk' },
      { name: 'soy milk' },
      { name: 'eggs', icon: '🥚' },
      { name: 'butter', icon: '🧈' },
      { name: 'margarine' },
      { name: 'cheese', icon: '🧀' },
      { name: 'cheddar', icon: '🧀' },
      { name: 'grated cheese' },
      { name: 'goat cheese' },
      { name: 'blue cheese' },
      { name: 'brie' },
      { name: 'manchego' },
      { name: 'mozzarella' },
      { name: 'parmesan' },
      { name: 'feta' },
      { name: 'ricotta' },
      { name: 'mascarpone' },
      { name: 'cream cheese' },
      { name: 'cottage cheese' },
      { name: 'yoghurt' },
      { name: 'greek yoghurt' },
      { name: 'kefir' },
      { name: 'cream' },
      { name: 'sour cream' },
      { name: 'creme fraiche' },
      { name: 'custard' },
      { name: 'condensed milk' },
    ],
  },
  {
    name: 'Meat & fish',
    icon: '🍗',
    items: [
      { name: 'chicken breast', icon: '🍗' },
      { name: 'chicken thighs', icon: '🍗' },
      { name: 'chicken wings', icon: '🍗' },
      { name: 'whole chicken', icon: '🍗' },
      { name: 'turkey' },
      { name: 'minced beef' },
      { name: 'beef steak', icon: '🥩' },
      { name: 'beef stewing' },
      { name: 'burger patties', icon: '🍔' },
      { name: 'meatballs' },
      { name: 'pork chops', icon: '🥩' },
      { name: 'pork belly' },
      { name: 'ribs' },
      { name: 'lamb' },
      { name: 'veal' },
      { name: 'duck' },
      { name: 'rabbit' },
      { name: 'sausages', icon: '🌭' },
      { name: 'bacon', icon: '🥓' },
      { name: 'ham' },
      { name: 'chorizo' },
      { name: 'salami' },
      { name: 'pate' },
      { name: 'black pudding' },
      { name: 'salmon', icon: '🐟' },
      { name: 'smoked salmon', icon: '🐟' },
      { name: 'white fish', icon: '🐟' },
      { name: 'cod' },
      { name: 'hake' },
      { name: 'sea bass' },
      { name: 'tuna steak', icon: '🐟' },
      { name: 'sardines', icon: '🐟' },
      { name: 'anchovies' },
      { name: 'prawns', icon: '🦐' },
      { name: 'mussels', icon: '🦪' },
      { name: 'clams' },
      { name: 'squid', icon: '🦑' },
      { name: 'octopus', icon: '🐙' },
      { name: 'crab', icon: '🦀' },
    ],
  },
  {
    name: 'Pantry',
    icon: '🥫',
    items: [
      { name: 'pasta', icon: '🍝' },
      { name: 'spaghetti', icon: '🍝' },
      { name: 'lasagne sheets' },
      { name: 'gnocchi' },
      { name: 'rice', icon: '🍚' },
      { name: 'risotto rice' },
      { name: 'noodles', icon: '🍜' },
      { name: 'rice noodles' },
      { name: 'couscous' },
      { name: 'quinoa' },
      { name: 'polenta' },
      { name: 'bulgur' },
      { name: 'lentils' },
      { name: 'chickpeas' },
      { name: 'kidney beans' },
      { name: 'white beans' },
      { name: 'tinned tomatoes', icon: '🥫' },
      { name: 'passata' },
      { name: 'tomato sauce', icon: '🥫' },
      { name: 'tomato puree' },
      { name: 'tinned tuna', icon: '🥫' },
      { name: 'tinned sweetcorn', icon: '🥫' },
      { name: 'coconut milk' },
      { name: 'olive oil', icon: '🫒' },
      { name: 'sunflower oil' },
      { name: 'sesame oil' },
      { name: 'vinegar' },
      { name: 'balsamic vinegar' },
      { name: 'salt', icon: '🧂' },
      { name: 'pepper' },
      { name: 'sugar' },
      { name: 'brown sugar' },
      { name: 'icing sugar' },
      { name: 'flour' },
      { name: 'cornflour' },
      { name: 'baking powder' },
      { name: 'yeast' },
      { name: 'vanilla' },
      { name: 'cocoa powder' },
      { name: 'chocolate chips' },
      { name: 'honey', icon: '🍯' },
      { name: 'jam' },
      { name: 'marmalade' },
      { name: 'peanut butter', icon: '🥜' },
      { name: 'chocolate spread' },
      { name: 'tahini' },
      { name: 'cereal', icon: '🥣' },
      { name: 'porridge oats', icon: '🥣' },
      { name: 'muesli' },
      { name: 'granola' },
      { name: 'stock cubes' },
      { name: 'soy sauce' },
      { name: 'fish sauce' },
      { name: 'worcestershire sauce' },
      { name: 'hot sauce' },
      { name: 'bbq sauce' },
      { name: 'mustard' },
      { name: 'mayonnaise' },
      { name: 'ketchup' },
      { name: 'pesto' },
      { name: 'curry paste' },
      { name: 'harissa' },
      { name: 'olives', icon: '🫒' },
      { name: 'pickles' },
      { name: 'capers' },
      { name: 'nuts', icon: '🥜' },
      { name: 'almonds' },
      { name: 'walnuts' },
      { name: 'cashews' },
      { name: 'pistachios' },
      { name: 'raisins' },
      { name: 'dates' },
      { name: 'dried apricots' },
      { name: 'chia seeds' },
      { name: 'sunflower seeds' },
      { name: 'pumpkin seeds' },
      { name: 'spices' },
      { name: 'paprika' },
      { name: 'oregano' },
      { name: 'thyme' },
      { name: 'bay leaves' },
      { name: 'cinnamon' },
      { name: 'nutmeg' },
      { name: 'cumin' },
      { name: 'turmeric' },
      { name: 'curry powder' },
      { name: 'chilli flakes' },
      { name: 'garlic powder' },
      { name: 'breadcrumbs' },
    ],
  },
  {
    name: 'Frozen',
    icon: '🧊',
    items: [
      { name: 'frozen peas' },
      { name: 'frozen spinach' },
      { name: 'frozen vegetables' },
      { name: 'frozen berries' },
      { name: 'frozen chips', icon: '🍟' },
      { name: 'frozen pizza', icon: '🍕' },
      { name: 'frozen fish' },
      { name: 'frozen prawns' },
      { name: 'frozen burgers' },
      { name: 'chicken nuggets' },
      { name: 'frozen pastry' },
      { name: 'frozen bread' },
      { name: 'ice cream', icon: '🍨' },
      { name: 'sorbet' },
      { name: 'ice cubes', icon: '🧊' },
    ],
  },
  {
    name: 'Drinks',
    icon: '🧃',
    items: [
      { name: 'water', icon: '💧' },
      { name: 'sparkling water' },
      { name: 'coconut water' },
      { name: 'orange juice', icon: '🧃' },
      { name: 'apple juice', icon: '🧃' },
      { name: 'lemonade' },
      { name: 'cola' },
      { name: 'soft drinks', icon: '🥤' },
      { name: 'tonic water' },
      { name: 'iced tea' },
      { name: 'energy drink' },
      { name: 'kombucha' },
      { name: 'coffee', icon: '☕' },
      { name: 'ground coffee', icon: '☕' },
      { name: 'coffee capsules', icon: '☕' },
      { name: 'tea', icon: '🍵' },
      { name: 'herbal tea', icon: '🍵' },
      { name: 'hot chocolate' },
      { name: 'red wine', icon: '🍷' },
      { name: 'white wine', icon: '🍷' },
      { name: 'rose wine', icon: '🍷' },
      { name: 'cava', icon: '🍾' },
      { name: 'beer', icon: '🍺' },
      { name: 'cider' },
      { name: 'vermouth' },
      { name: 'gin' },
      { name: 'whisky', icon: '🥃' },
      { name: 'rum' },
      { name: 'vodka' },
    ],
  },
  {
    name: 'Snacks',
    icon: '🍫',
    items: [
      { name: 'crisps' },
      { name: 'tortilla chips' },
      { name: 'nachos' },
      { name: 'pretzels', icon: '🥨' },
      { name: 'popcorn', icon: '🍿' },
      { name: 'crackers' },
      { name: 'breadsticks' },
      { name: 'rice cakes' },
      { name: 'chocolate', icon: '🍫' },
      { name: 'sweets', icon: '🍬' },
      { name: 'chewing gum' },
      { name: 'marshmallows' },
      { name: 'cereal bars' },
      { name: 'dried fruit' },
      { name: 'salsa' },
      { name: 'guacamole' },
      { name: 'hummus' },
    ],
  },
  {
    name: 'Household',
    icon: '🧻',
    items: [
      { name: 'toilet paper', icon: '🧻' },
      { name: 'kitchen roll', icon: '🧻' },
      { name: 'tissues' },
      { name: 'bin bags', icon: '🗑️' },
      { name: 'food bags' },
      { name: 'freezer bags' },
      { name: 'cling film' },
      { name: 'aluminium foil' },
      { name: 'baking paper' },
      { name: 'washing up liquid', icon: '🧽' },
      { name: 'dishwasher tablets' },
      { name: 'dish cloths' },
      { name: 'sponges', icon: '🧽' },
      { name: 'scourers' },
      { name: 'rubber gloves', icon: '🧤' },
      { name: 'laundry detergent', icon: '🧺' },
      { name: 'fabric softener' },
      { name: 'stain remover' },
      { name: 'surface cleaner', icon: '🧴' },
      { name: 'bleach' },
      { name: 'toilet cleaner' },
      { name: 'oven cleaner' },
      { name: 'window cleaner' },
      { name: 'air freshener' },
      { name: 'insect spray' },
      { name: 'batteries', icon: '🔋' },
      { name: 'light bulbs', icon: '💡' },
      { name: 'candles', icon: '🕯️' },
      { name: 'matches' },
      { name: 'tape' },
    ],
  },
  {
    name: 'Personal care',
    icon: '🧼',
    items: [
      { name: 'shampoo', icon: '🧴' },
      { name: 'conditioner', icon: '🧴' },
      { name: 'shower gel', icon: '🧴' },
      { name: 'soap', icon: '🧼' },
      { name: 'hand soap', icon: '🧼' },
      { name: 'hand sanitiser' },
      { name: 'hand cream' },
      { name: 'moisturiser' },
      { name: 'lip balm' },
      { name: 'sun cream', icon: '🧴' },
      { name: 'deodorant' },
      { name: 'toothpaste', icon: '🪥' },
      { name: 'toothbrush', icon: '🪥' },
      { name: 'mouthwash' },
      { name: 'dental floss' },
      { name: 'razors', icon: '🪒' },
      { name: 'shaving foam' },
      { name: 'hairbrush' },
      { name: 'hair gel' },
      { name: 'cotton buds' },
      { name: 'cotton pads' },
      { name: 'wet wipes' },
      { name: 'nail clippers' },
      { name: 'sanitary pads' },
      { name: 'tampons' },
      { name: 'plasters', icon: '🩹' },
      { name: 'antiseptic cream' },
      { name: 'paracetamol', icon: '💊' },
      { name: 'ibuprofen', icon: '💊' },
      { name: 'throat lozenges' },
      { name: 'vitamins', icon: '💊' },
    ],
  },
]

/** Every seed item flattened, with its category and grid position attached. */
export function flattenSeed(): {
  name: string
  category: string
  icon: string | null
  sortOrder: number
}[] {
  const rows: { name: string; category: string; icon: string | null; sortOrder: number }[] = []

  CATALOGUE_SEED.forEach((category, categoryIndex) => {
    category.items.forEach((item, itemIndex) => {
      rows.push({
        name: item.name,
        category: category.name,
        icon: item.icon ?? null,
        // Category first, then position within it. The 1000 gap leaves room to
        // insert items into a category later without renumbering everything.
        sortOrder: categoryIndex * 1000 + itemIndex,
      })
    })
  })

  return rows
}
