/*
 * Which OpenMoji file draws which emoji.
 *
 * Generated by scripts/fetch-openmoji.mjs — do not edit by hand. Re-run the
 * script after adding an emoji to the catalogue seed.
 *
 * The values are filenames under public/openmoji/, which is OpenMoji's own
 * codepoint naming. Keeping the map explicit rather than computing codepoints at
 * runtime means a missing file is caught here, once, instead of showing up as a
 * broken image on someone's phone.
 *
 * OpenMoji 17.0.0 — https://openmoji.org — CC BY-SA 4.0. See docs/OPENMOJI.md.
 */

/** Emoji character to OpenMoji filename stem. */
export const OPENMOJI: Readonly<Record<string, string>> = {
  '☕': '2615',
  '🌭': '1F32D',
  '🌯': '1F32F',
  '🌶️': '1F336',
  '🌽': '1F33D',
  '🌿': '1F33F',
  '🍄': '1F344',
  '🍅': '1F345',
  '🍆': '1F346',
  '🍇': '1F347',
  '🍈': '1F348',
  '🍉': '1F349',
  '🍊': '1F34A',
  '🍋': '1F34B',
  '🍌': '1F34C',
  '🍍': '1F34D',
  '🍎': '1F34E',
  '🍐': '1F350',
  '🍑': '1F351',
  '🍒': '1F352',
  '🍓': '1F353',
  '🍔': '1F354',
  '🍕': '1F355',
  '🍗': '1F357',
  '🍚': '1F35A',
  '🍜': '1F35C',
  '🍝': '1F35D',
  '🍞': '1F35E',
  '🍟': '1F35F',
  '🍠': '1F360',
  '🍨': '1F368',
  '🍩': '1F369',
  '🍪': '1F36A',
  '🍫': '1F36B',
  '🍬': '1F36C',
  '🍯': '1F36F',
  '🍰': '1F370',
  '🍵': '1F375',
  '🍷': '1F377',
  '🍺': '1F37A',
  '🍾': '1F37E',
  '🍿': '1F37F',
  '🎃': '1F383',
  '🐙': '1F419',
  '🐟': '1F41F',
  '💊': '1F48A',
  '💡': '1F4A1',
  '💧': '1F4A7',
  '🔋': '1F50B',
  '🕯️': '1F56F',
  '🗑️': '1F5D1',
  '🥃': '1F943',
  '🥐': '1F950',
  '🥑': '1F951',
  '🥒': '1F952',
  '🥓': '1F953',
  '🥔': '1F954',
  '🥕': '1F955',
  '🥖': '1F956',
  '🥚': '1F95A',
  '🥛': '1F95B',
  '🥜': '1F95C',
  '🥝': '1F95D',
  '🥣': '1F963',
  '🥤': '1F964',
  '🥦': '1F966',
  '🥧': '1F967',
  '🥨': '1F968',
  '🥩': '1F969',
  '🥫': '1F96B',
  '🥬': '1F96C',
  '🥭': '1F96D',
  '🥯': '1F96F',
  '🦀': '1F980',
  '🦐': '1F990',
  '🦑': '1F991',
  '🦪': '1F9AA',
  '🧀': '1F9C0',
  '🧁': '1F9C1',
  '🧂': '1F9C2',
  '🧃': '1F9C3',
  '🧄': '1F9C4',
  '🧅': '1F9C5',
  '🧈': '1F9C8',
  '🧊': '1F9CA',
  '🧤': '1F9E4',
  '🧴': '1F9F4',
  '🧺': '1F9FA',
  '🧻': '1F9FB',
  '🧼': '1F9FC',
  '🧽': '1F9FD',
  '🩹': '1FA79',
  '🪒': '1FA92',
  '🪥': '1FAA5',
  '🫐': '1FAD0',
  '🫑': '1FAD1',
  '🫒': '1FAD2',
}

/** Where the drawing for this emoji lives, or null if we don't ship one. */
export function openmojiSrc(emoji: string | null): string | null {
  if (!emoji) return null
  const code = OPENMOJI[emoji]
  return code ? `${import.meta.env.BASE_URL}openmoji/${code}.svg` : null
}

/** Every emoji we have a drawing for, in catalogue order. */
export const OPENMOJI_EMOJI: readonly string[] = Object.keys(OPENMOJI)
