-- Round 3: the seeded catalogue — the tiles you tap instead of typing.
--
-- GENERATED FILE. Do not edit by hand: change src/lib/catalogue-seed.ts and run
-- `npm run seed:sql`. 361 items across 10 categories.
--
-- These rows have household_id null, meaning they are shared by every
-- household and belong to none. The insert policy in 0002 deliberately forbids
-- creating rows like that from the app, so this has to be run here, in the SQL
-- editor, where policies don't apply.
--
-- Safe to re-run: on conflict it updates the category, icon and order, so
-- re-running after re-ordering the catalogue applies the new order rather than
-- erroring or duplicating.

insert into public.catalogue_items (name, category, icon, sort_order)
values
  ('apples', 'Fruit & vegetables', '🍎', 0),
  ('bananas', 'Fruit & vegetables', '🍌', 1),
  ('oranges', 'Fruit & vegetables', '🍊', 2),
  ('lemons', 'Fruit & vegetables', '🍋', 3),
  ('limes', 'Fruit & vegetables', null, 4),
  ('strawberries', 'Fruit & vegetables', '🍓', 5),
  ('raspberries', 'Fruit & vegetables', null, 6),
  ('blueberries', 'Fruit & vegetables', '🫐', 7),
  ('grapes', 'Fruit & vegetables', '🍇', 8),
  ('cherries', 'Fruit & vegetables', '🍒', 9),
  ('melon', 'Fruit & vegetables', '🍈', 10),
  ('watermelon', 'Fruit & vegetables', '🍉', 11),
  ('peaches', 'Fruit & vegetables', '🍑', 12),
  ('pears', 'Fruit & vegetables', '🍐', 13),
  ('plums', 'Fruit & vegetables', null, 14),
  ('apricots', 'Fruit & vegetables', null, 15),
  ('figs', 'Fruit & vegetables', null, 16),
  ('pineapple', 'Fruit & vegetables', '🍍', 17),
  ('kiwi', 'Fruit & vegetables', '🥝', 18),
  ('mango', 'Fruit & vegetables', '🥭', 19),
  ('pomegranate', 'Fruit & vegetables', null, 20),
  ('avocado', 'Fruit & vegetables', '🥑', 21),
  ('tomatoes', 'Fruit & vegetables', '🍅', 22),
  ('cherry tomatoes', 'Fruit & vegetables', '🍅', 23),
  ('potatoes', 'Fruit & vegetables', '🥔', 24),
  ('sweet potato', 'Fruit & vegetables', '🍠', 25),
  ('onions', 'Fruit & vegetables', '🧅', 26),
  ('spring onions', 'Fruit & vegetables', null, 27),
  ('garlic', 'Fruit & vegetables', '🧄', 28),
  ('carrots', 'Fruit & vegetables', '🥕', 29),
  ('peppers', 'Fruit & vegetables', '🫑', 30),
  ('chillies', 'Fruit & vegetables', '🌶️', 31),
  ('courgette', 'Fruit & vegetables', '🥒', 32),
  ('aubergine', 'Fruit & vegetables', '🍆', 33),
  ('cucumber', 'Fruit & vegetables', '🥒', 34),
  ('lettuce', 'Fruit & vegetables', '🥬', 35),
  ('rocket', 'Fruit & vegetables', null, 36),
  ('spinach', 'Fruit & vegetables', '🥬', 37),
  ('broccoli', 'Fruit & vegetables', '🥦', 38),
  ('cauliflower', 'Fruit & vegetables', null, 39),
  ('cabbage', 'Fruit & vegetables', null, 40),
  ('brussels sprouts', 'Fruit & vegetables', null, 41),
  ('asparagus', 'Fruit & vegetables', null, 42),
  ('artichoke', 'Fruit & vegetables', null, 43),
  ('fennel', 'Fruit & vegetables', null, 44),
  ('mushrooms', 'Fruit & vegetables', '🍄', 45),
  ('sweetcorn', 'Fruit & vegetables', '🌽', 46),
  ('green beans', 'Fruit & vegetables', null, 47),
  ('peas', 'Fruit & vegetables', null, 48),
  ('leek', 'Fruit & vegetables', null, 49),
  ('celery', 'Fruit & vegetables', null, 50),
  ('radish', 'Fruit & vegetables', null, 51),
  ('beetroot', 'Fruit & vegetables', null, 52),
  ('pumpkin', 'Fruit & vegetables', '🎃', 53),
  ('ginger', 'Fruit & vegetables', null, 54),
  ('parsley', 'Fruit & vegetables', '🌿', 55),
  ('basil', 'Fruit & vegetables', '🌿', 56),
  ('coriander', 'Fruit & vegetables', '🌿', 57),
  ('mint', 'Fruit & vegetables', '🌿', 58),
  ('rosemary', 'Fruit & vegetables', '🌿', 59),
  ('salad bag', 'Fruit & vegetables', null, 60),
  ('bread', 'Bakery', '🍞', 1000),
  ('baguette', 'Bakery', '🥖', 1001),
  ('sliced bread', 'Bakery', null, 1002),
  ('wholemeal bread', 'Bakery', null, 1003),
  ('sourdough', 'Bakery', null, 1004),
  ('bread rolls', 'Bakery', null, 1005),
  ('ciabatta', 'Bakery', null, 1006),
  ('focaccia', 'Bakery', null, 1007),
  ('brioche', 'Bakery', null, 1008),
  ('croissants', 'Bakery', '🥐', 1009),
  ('bagels', 'Bakery', '🥯', 1010),
  ('pitta bread', 'Bakery', null, 1011),
  ('naan', 'Bakery', null, 1012),
  ('tortillas', 'Bakery', '🌯', 1013),
  ('pastries', 'Bakery', '🥧', 1014),
  ('cake', 'Bakery', '🍰', 1015),
  ('muffins', 'Bakery', '🧁', 1016),
  ('doughnuts', 'Bakery', '🍩', 1017),
  ('scones', 'Bakery', null, 1018),
  ('biscuits', 'Bakery', '🍪', 1019),
  ('milk', 'Dairy & eggs', '🥛', 2000),
  ('semi-skimmed milk', 'Dairy & eggs', null, 2001),
  ('oat milk', 'Dairy & eggs', null, 2002),
  ('almond milk', 'Dairy & eggs', null, 2003),
  ('soy milk', 'Dairy & eggs', null, 2004),
  ('eggs', 'Dairy & eggs', '🥚', 2005),
  ('butter', 'Dairy & eggs', '🧈', 2006),
  ('margarine', 'Dairy & eggs', null, 2007),
  ('cheese', 'Dairy & eggs', '🧀', 2008),
  ('cheddar', 'Dairy & eggs', '🧀', 2009),
  ('grated cheese', 'Dairy & eggs', null, 2010),
  ('goat cheese', 'Dairy & eggs', null, 2011),
  ('blue cheese', 'Dairy & eggs', null, 2012),
  ('brie', 'Dairy & eggs', null, 2013),
  ('manchego', 'Dairy & eggs', null, 2014),
  ('mozzarella', 'Dairy & eggs', null, 2015),
  ('parmesan', 'Dairy & eggs', null, 2016),
  ('feta', 'Dairy & eggs', null, 2017),
  ('ricotta', 'Dairy & eggs', null, 2018),
  ('mascarpone', 'Dairy & eggs', null, 2019),
  ('cream cheese', 'Dairy & eggs', null, 2020),
  ('cottage cheese', 'Dairy & eggs', null, 2021),
  ('yoghurt', 'Dairy & eggs', null, 2022),
  ('greek yoghurt', 'Dairy & eggs', null, 2023),
  ('kefir', 'Dairy & eggs', null, 2024),
  ('cream', 'Dairy & eggs', null, 2025),
  ('sour cream', 'Dairy & eggs', null, 2026),
  ('creme fraiche', 'Dairy & eggs', null, 2027),
  ('custard', 'Dairy & eggs', null, 2028),
  ('condensed milk', 'Dairy & eggs', null, 2029),
  ('chicken breast', 'Meat & fish', '🍗', 3000),
  ('chicken thighs', 'Meat & fish', '🍗', 3001),
  ('chicken wings', 'Meat & fish', '🍗', 3002),
  ('whole chicken', 'Meat & fish', '🍗', 3003),
  ('turkey', 'Meat & fish', null, 3004),
  ('minced beef', 'Meat & fish', null, 3005),
  ('beef steak', 'Meat & fish', '🥩', 3006),
  ('beef stewing', 'Meat & fish', null, 3007),
  ('burger patties', 'Meat & fish', '🍔', 3008),
  ('meatballs', 'Meat & fish', null, 3009),
  ('pork chops', 'Meat & fish', '🥩', 3010),
  ('pork belly', 'Meat & fish', null, 3011),
  ('ribs', 'Meat & fish', null, 3012),
  ('lamb', 'Meat & fish', null, 3013),
  ('veal', 'Meat & fish', null, 3014),
  ('duck', 'Meat & fish', null, 3015),
  ('rabbit', 'Meat & fish', null, 3016),
  ('sausages', 'Meat & fish', '🌭', 3017),
  ('bacon', 'Meat & fish', '🥓', 3018),
  ('ham', 'Meat & fish', null, 3019),
  ('chorizo', 'Meat & fish', null, 3020),
  ('salami', 'Meat & fish', null, 3021),
  ('pate', 'Meat & fish', null, 3022),
  ('black pudding', 'Meat & fish', null, 3023),
  ('salmon', 'Meat & fish', '🐟', 3024),
  ('smoked salmon', 'Meat & fish', '🐟', 3025),
  ('white fish', 'Meat & fish', '🐟', 3026),
  ('cod', 'Meat & fish', null, 3027),
  ('hake', 'Meat & fish', null, 3028),
  ('sea bass', 'Meat & fish', null, 3029),
  ('tuna steak', 'Meat & fish', '🐟', 3030),
  ('sardines', 'Meat & fish', '🐟', 3031),
  ('anchovies', 'Meat & fish', null, 3032),
  ('prawns', 'Meat & fish', '🦐', 3033),
  ('mussels', 'Meat & fish', '🦪', 3034),
  ('clams', 'Meat & fish', null, 3035),
  ('squid', 'Meat & fish', '🦑', 3036),
  ('octopus', 'Meat & fish', '🐙', 3037),
  ('crab', 'Meat & fish', '🦀', 3038),
  ('pasta', 'Pantry', '🍝', 4000),
  ('spaghetti', 'Pantry', '🍝', 4001),
  ('lasagne sheets', 'Pantry', null, 4002),
  ('gnocchi', 'Pantry', null, 4003),
  ('rice', 'Pantry', '🍚', 4004),
  ('risotto rice', 'Pantry', null, 4005),
  ('noodles', 'Pantry', '🍜', 4006),
  ('rice noodles', 'Pantry', null, 4007),
  ('couscous', 'Pantry', null, 4008),
  ('quinoa', 'Pantry', null, 4009),
  ('polenta', 'Pantry', null, 4010),
  ('bulgur', 'Pantry', null, 4011),
  ('lentils', 'Pantry', null, 4012),
  ('chickpeas', 'Pantry', null, 4013),
  ('kidney beans', 'Pantry', null, 4014),
  ('white beans', 'Pantry', null, 4015),
  ('tinned tomatoes', 'Pantry', '🥫', 4016),
  ('passata', 'Pantry', null, 4017),
  ('tomato sauce', 'Pantry', '🥫', 4018),
  ('tomato puree', 'Pantry', null, 4019),
  ('tinned tuna', 'Pantry', '🥫', 4020),
  ('tinned sweetcorn', 'Pantry', '🥫', 4021),
  ('coconut milk', 'Pantry', null, 4022),
  ('olive oil', 'Pantry', '🫒', 4023),
  ('sunflower oil', 'Pantry', null, 4024),
  ('sesame oil', 'Pantry', null, 4025),
  ('vinegar', 'Pantry', null, 4026),
  ('balsamic vinegar', 'Pantry', null, 4027),
  ('salt', 'Pantry', '🧂', 4028),
  ('pepper', 'Pantry', null, 4029),
  ('sugar', 'Pantry', null, 4030),
  ('brown sugar', 'Pantry', null, 4031),
  ('icing sugar', 'Pantry', null, 4032),
  ('flour', 'Pantry', null, 4033),
  ('cornflour', 'Pantry', null, 4034),
  ('baking powder', 'Pantry', null, 4035),
  ('yeast', 'Pantry', null, 4036),
  ('vanilla', 'Pantry', null, 4037),
  ('cocoa powder', 'Pantry', null, 4038),
  ('chocolate chips', 'Pantry', null, 4039),
  ('honey', 'Pantry', '🍯', 4040),
  ('jam', 'Pantry', null, 4041),
  ('marmalade', 'Pantry', null, 4042),
  ('peanut butter', 'Pantry', '🥜', 4043),
  ('chocolate spread', 'Pantry', null, 4044),
  ('tahini', 'Pantry', null, 4045),
  ('cereal', 'Pantry', '🥣', 4046),
  ('porridge oats', 'Pantry', '🥣', 4047),
  ('muesli', 'Pantry', null, 4048),
  ('granola', 'Pantry', null, 4049),
  ('stock cubes', 'Pantry', null, 4050),
  ('soy sauce', 'Pantry', null, 4051),
  ('fish sauce', 'Pantry', null, 4052),
  ('worcestershire sauce', 'Pantry', null, 4053),
  ('hot sauce', 'Pantry', null, 4054),
  ('bbq sauce', 'Pantry', null, 4055),
  ('mustard', 'Pantry', null, 4056),
  ('mayonnaise', 'Pantry', null, 4057),
  ('ketchup', 'Pantry', null, 4058),
  ('pesto', 'Pantry', null, 4059),
  ('curry paste', 'Pantry', null, 4060),
  ('harissa', 'Pantry', null, 4061),
  ('olives', 'Pantry', '🫒', 4062),
  ('pickles', 'Pantry', null, 4063),
  ('capers', 'Pantry', null, 4064),
  ('nuts', 'Pantry', '🥜', 4065),
  ('almonds', 'Pantry', null, 4066),
  ('walnuts', 'Pantry', null, 4067),
  ('cashews', 'Pantry', null, 4068),
  ('pistachios', 'Pantry', null, 4069),
  ('raisins', 'Pantry', null, 4070),
  ('dates', 'Pantry', null, 4071),
  ('dried apricots', 'Pantry', null, 4072),
  ('chia seeds', 'Pantry', null, 4073),
  ('sunflower seeds', 'Pantry', null, 4074),
  ('pumpkin seeds', 'Pantry', null, 4075),
  ('spices', 'Pantry', null, 4076),
  ('paprika', 'Pantry', null, 4077),
  ('oregano', 'Pantry', null, 4078),
  ('thyme', 'Pantry', null, 4079),
  ('bay leaves', 'Pantry', null, 4080),
  ('cinnamon', 'Pantry', null, 4081),
  ('nutmeg', 'Pantry', null, 4082),
  ('cumin', 'Pantry', null, 4083),
  ('turmeric', 'Pantry', null, 4084),
  ('curry powder', 'Pantry', null, 4085),
  ('chilli flakes', 'Pantry', null, 4086),
  ('garlic powder', 'Pantry', null, 4087),
  ('breadcrumbs', 'Pantry', null, 4088),
  ('frozen peas', 'Frozen', null, 5000),
  ('frozen spinach', 'Frozen', null, 5001),
  ('frozen vegetables', 'Frozen', null, 5002),
  ('frozen berries', 'Frozen', null, 5003),
  ('frozen chips', 'Frozen', '🍟', 5004),
  ('frozen pizza', 'Frozen', '🍕', 5005),
  ('frozen fish', 'Frozen', null, 5006),
  ('frozen prawns', 'Frozen', null, 5007),
  ('frozen burgers', 'Frozen', null, 5008),
  ('chicken nuggets', 'Frozen', null, 5009),
  ('frozen pastry', 'Frozen', null, 5010),
  ('frozen bread', 'Frozen', null, 5011),
  ('ice cream', 'Frozen', '🍨', 5012),
  ('sorbet', 'Frozen', null, 5013),
  ('ice cubes', 'Frozen', '🧊', 5014),
  ('water', 'Drinks', '💧', 6000),
  ('sparkling water', 'Drinks', null, 6001),
  ('coconut water', 'Drinks', null, 6002),
  ('orange juice', 'Drinks', '🧃', 6003),
  ('apple juice', 'Drinks', '🧃', 6004),
  ('lemonade', 'Drinks', null, 6005),
  ('cola', 'Drinks', null, 6006),
  ('soft drinks', 'Drinks', '🥤', 6007),
  ('tonic water', 'Drinks', null, 6008),
  ('iced tea', 'Drinks', null, 6009),
  ('energy drink', 'Drinks', null, 6010),
  ('kombucha', 'Drinks', null, 6011),
  ('coffee', 'Drinks', '☕', 6012),
  ('ground coffee', 'Drinks', '☕', 6013),
  ('coffee capsules', 'Drinks', '☕', 6014),
  ('tea', 'Drinks', '🍵', 6015),
  ('herbal tea', 'Drinks', '🍵', 6016),
  ('hot chocolate', 'Drinks', null, 6017),
  ('red wine', 'Drinks', '🍷', 6018),
  ('white wine', 'Drinks', '🍷', 6019),
  ('rose wine', 'Drinks', '🍷', 6020),
  ('cava', 'Drinks', '🍾', 6021),
  ('beer', 'Drinks', '🍺', 6022),
  ('cider', 'Drinks', null, 6023),
  ('vermouth', 'Drinks', null, 6024),
  ('gin', 'Drinks', null, 6025),
  ('whisky', 'Drinks', '🥃', 6026),
  ('rum', 'Drinks', null, 6027),
  ('vodka', 'Drinks', null, 6028),
  ('crisps', 'Snacks', null, 7000),
  ('tortilla chips', 'Snacks', null, 7001),
  ('nachos', 'Snacks', null, 7002),
  ('pretzels', 'Snacks', '🥨', 7003),
  ('popcorn', 'Snacks', '🍿', 7004),
  ('crackers', 'Snacks', null, 7005),
  ('breadsticks', 'Snacks', null, 7006),
  ('rice cakes', 'Snacks', null, 7007),
  ('chocolate', 'Snacks', '🍫', 7008),
  ('sweets', 'Snacks', '🍬', 7009),
  ('chewing gum', 'Snacks', null, 7010),
  ('marshmallows', 'Snacks', null, 7011),
  ('cereal bars', 'Snacks', null, 7012),
  ('dried fruit', 'Snacks', null, 7013),
  ('salsa', 'Snacks', null, 7014),
  ('guacamole', 'Snacks', null, 7015),
  ('hummus', 'Snacks', null, 7016),
  ('toilet paper', 'Household', '🧻', 8000),
  ('kitchen roll', 'Household', '🧻', 8001),
  ('tissues', 'Household', null, 8002),
  ('bin bags', 'Household', '🗑️', 8003),
  ('food bags', 'Household', null, 8004),
  ('freezer bags', 'Household', null, 8005),
  ('cling film', 'Household', null, 8006),
  ('aluminium foil', 'Household', null, 8007),
  ('baking paper', 'Household', null, 8008),
  ('washing up liquid', 'Household', '🧽', 8009),
  ('dishwasher tablets', 'Household', null, 8010),
  ('dish cloths', 'Household', null, 8011),
  ('sponges', 'Household', '🧽', 8012),
  ('scourers', 'Household', null, 8013),
  ('rubber gloves', 'Household', '🧤', 8014),
  ('laundry detergent', 'Household', '🧺', 8015),
  ('fabric softener', 'Household', null, 8016),
  ('stain remover', 'Household', null, 8017),
  ('surface cleaner', 'Household', '🧴', 8018),
  ('bleach', 'Household', null, 8019),
  ('toilet cleaner', 'Household', null, 8020),
  ('oven cleaner', 'Household', null, 8021),
  ('window cleaner', 'Household', null, 8022),
  ('air freshener', 'Household', null, 8023),
  ('insect spray', 'Household', null, 8024),
  ('batteries', 'Household', '🔋', 8025),
  ('light bulbs', 'Household', '💡', 8026),
  ('candles', 'Household', '🕯️', 8027),
  ('matches', 'Household', null, 8028),
  ('tape', 'Household', null, 8029),
  ('shampoo', 'Personal care', '🧴', 9000),
  ('conditioner', 'Personal care', '🧴', 9001),
  ('shower gel', 'Personal care', '🧴', 9002),
  ('soap', 'Personal care', '🧼', 9003),
  ('hand soap', 'Personal care', '🧼', 9004),
  ('hand sanitiser', 'Personal care', null, 9005),
  ('hand cream', 'Personal care', null, 9006),
  ('moisturiser', 'Personal care', null, 9007),
  ('lip balm', 'Personal care', null, 9008),
  ('sun cream', 'Personal care', '🧴', 9009),
  ('deodorant', 'Personal care', null, 9010),
  ('toothpaste', 'Personal care', '🪥', 9011),
  ('toothbrush', 'Personal care', '🪥', 9012),
  ('mouthwash', 'Personal care', null, 9013),
  ('dental floss', 'Personal care', null, 9014),
  ('razors', 'Personal care', '🪒', 9015),
  ('shaving foam', 'Personal care', null, 9016),
  ('hairbrush', 'Personal care', null, 9017),
  ('hair gel', 'Personal care', null, 9018),
  ('cotton buds', 'Personal care', null, 9019),
  ('cotton pads', 'Personal care', null, 9020),
  ('wet wipes', 'Personal care', null, 9021),
  ('nail clippers', 'Personal care', null, 9022),
  ('sanitary pads', 'Personal care', null, 9023),
  ('tampons', 'Personal care', null, 9024),
  ('plasters', 'Personal care', '🩹', 9025),
  ('antiseptic cream', 'Personal care', null, 9026),
  ('paracetamol', 'Personal care', '💊', 9027),
  ('ibuprofen', 'Personal care', '💊', 9028),
  ('throat lozenges', 'Personal care', null, 9029),
  ('vitamins', 'Personal care', '💊', 9030)
on conflict (lower(trim(name))) where household_id is null
do update set
  category = excluded.category,
  icon = excluded.icon,
  sort_order = excluded.sort_order;
